기념일 관리 기능 구현 및 테스트 코드 추가
bit-o-gi/bitO-BE-Project pull request #61
Opened 2024-11-13 06:00 UTC by bong94688

#### 주요 구현 사항
1. **기념일 생성, 조회, 수정, 삭제 기능 구현**
   - `AnReqDto -> AnDto -> Anniversary` 변환 과정을 통해 요청 데이터를 기념일 엔티티로 변환 및 처리하는 로직 구현.
   - `AnResDto`로 반환하여 클라이언트와의 데이터 교환 형식 일관성 유지.

2. **특정 날짜 범위 내, 특정 날짜 이전 및 이후 기념일 조회 기능 구현**
   - `AnRepository`에 날짜 범위 내에서 기념일을 조회하는 메서드를 정의하여 기간별 조회가 가능하도록 지원.
   
3. **알림 전송 기능 (UDP 방식) 구현**
   - 기념일 알림 전송을 위한 `DatagramSocket`을 사용한 UDP 전송 방식 구현.
   
4. **반복 기념일 계산 기능 추가**
   - 매년 반복되는 기념일의 다음 기념일 날짜를 계산하는 메서드 구현.

#### 테스트 코드 추가
1. **AnService 테스트 코드**
   - 기념일 생성, 조회, 수정, 삭제에 대한 기본적인 기능 테스트 코드 추가.
   - `ModelMapper`를 활용한 `AnReqDto -> AnDto -> Anniversary` 변환 과정에 대한 검증 포함.
   
2. **AnRepository 테스트 코드**
   - 특정 날짜 범위 내, 특정 날짜 이전 및 이후의 기념일 조회 테스트 코드 작성.
   - `@DataJpaTest`를 사용하여 JPA 레포지토리의 정확한 동작을 검증.
   
3. **기타 테스트 개선**
   - 각 필드의 setter 사용을 지양하고 변환 로직을 `ModelMapper`와 builder 패턴으로 일관되게 처리.
   - DisplayName을 한글로 작성하여 테스트 가독성을 높임.

#### 기타
- `ModelMapper` 설정을 추가하여 Dto 간 변환을 효율적으로 수행.
- 기념일 관리 기능과 관련된 GraphQL 타입 및 쿼리, 뮤테이션 정의 추가.
  
#### 주의사항
- 일부 로직은 setter 사용 없이 ModelMapper를 활용해 변환하는 방식으로 일관성을 유지했습니다.
  
기능 구현 및 테스트 코드가 안정적으로 작성되었으므로, 코드 리뷰를 통해 추가적인 개선 사항 확인 바랍니다.

2024-11-14 02:31 UTC, ParkSeryu requested changes

2024-11-14 02:31 UTC, ParkSeryu commented on src/main/java/bit/anniversary/controller/AnController.java
> +		return true;
왜 dto에서 boolean으로 바뀐걸까요??

2024-11-14 02:31 UTC, ParkSeryu commented on src/main/java/bit/anniversary/controller/AnController.java
> +	public List<AnResDto> getAnniversariesInRange(@Argument LocalDateTime startDate, @Argument LocalDateTime endDate) {
GraphQL에는 dto로 받는 그런게 따로 있나요?
원래같았으면 requestDto라던지를 받아서 request받는 갯수를 제어했을거같아서 여쭤봅니당

2024-11-14 02:31 UTC, ParkSeryu commented on src/main/java/bit/anniversary/controller/AnController.java
> +	}
**P2**
한달이나 1년같은거는 기획적으로 정책이 바뀌거나 하면 바뀔수 있는 부분이라고 봐요
상수로 하기보다는 매개변수로 받는다던가 아니면 컨트롤할수 있는 부분으로 만드는게 어떨까요?

2024-11-14 02:31 UTC, ParkSeryu commented on src/main/java/bit/anniversary/dto/AnDto.java
@Setter가 없으면 안되는 이유는 알아내셨나요~?

2024-11-14 02:31 UTC, ParkSeryu commented on src/test/java/bit/anniversary/service/AnServiceTest.java
> +		withPeopleEntity = UserEntity.from(withPeople);
**P2**
기존에 있는 Fixture를 활용하거나,
새로운 Fixture를 만드는게 어떨까요?

2024-11-14 02:31 UTC, ParkSeryu commented on src/test/java/bit/anniversary/controller/AnControllerTest.java
무슨 케이스를 검증하려고 하신걸까요?

2024-11-14 02:31 UTC, ParkSeryu commented on src/test/java/bit/anniversary/repository/AnRepositoryTest.java
좋은 테스트코드라고 생각합니다!

2024-11-14 02:38 UTC, bong94688 commented on src/main/java/bit/anniversary/controller/AnController.java
> +		return true;
필요없는 정보를 제거하기위해 boolean 으로 바꿨습니다.
이미 있는 데이터를 그대로 보내주는건 불 필요 하다 생각했습니다.

2024-11-14 02:40 UTC, bong94688 commented on src/main/java/bit/anniversary/controller/AnController.java
> +	public List<AnResDto> getAnniversariesInRange(@Argument LocalDateTime startDate, @Argument LocalDateTime endDate) {
gaphql 에서 정의만 한다면 어떤 형태로 받는지는 크게 상관없습니다.  
그렇지만 받는형태에 따라 Dto가 많이 늘어갈것 같아서 저런 기초적인 형태는 Dto 를 사용하지 않을까 합니다.

2024-11-14 02:41 UTC, bong94688 commented on src/main/java/bit/anniversary/controller/AnController.java
> +	}
기획적으로 바뀔수 있지만 현재 만들어진 켈린더 기능에서 사용하기위한 한달 조회 기능이구여 
일년 조회 기능은 도 동일하게 켈린더 기능을 위함입니다.
PS
이미 StartDate , EndDate 를 이용한 기간 조회 기능은 있습니다.

2024-11-14 02:44 UTC, bong94688 commented on src/main/java/bit/anniversary/dto/AnDto.java
아직 이유는 못알았지만 Graphqls <-> dto 간에 관계에서 자동적으로 하기위함 일것같습니다. 추가적인 사항은 이슈로 다루겠습니다.

2024-11-14 02:45 UTC, bong94688 commented on src/test/java/bit/anniversary/service/AnServiceTest.java
> +		withPeopleEntity = UserEntity.from(withPeople);
아직 User 코드를 잘 읽어보지못하여 직관적으로 짜낸 코드입니다

2024-11-14 03:43 UTC, ParkSeryu commented on src/main/java/bit/anniversary/controller/AnController.java
> +		return true;
FE가 봤을땐 불린값만 돌아오는게 조금 당황스러울 수 있을것도 같은데, 
ResponseEntity같은걸로 랩핑하는건 어떨까용

2024-11-14 03:44 UTC, ParkSeryu commented on src/main/java/bit/anniversary/controller/AnController.java
> +	}
캘린더 기능이라는게 뭔지 설명좀 해주실수 있나요?

2024-11-14 03:48 UTC, ParkSeryu commented on src/test/java/bit/anniversary/service/AnServiceTest.java
> +		withPeopleEntity = UserEntity.from(withPeople);
말의 요지는,
해당코드가 보일러플레이트 비슷하게 반복되고있어, 따로 빼서 묶자는 의미입니다

2024-11-14 04:11 UTC, bong94688 commented on src/main/java/bit/anniversary/controller/AnController.java
> +		return true;
추후 리펙토링으로 tranSactionId 와 timestamp 등 넣은형태로 Resonpse 를 줄 예정입니다. 이 이슈는 #63 으로 다루겠습니다.

2024-11-14 04:11 UTC, bong94688 commented on src/test/java/bit/anniversary/service/AnServiceTest.java
> +		withPeopleEntity = UserEntity.from(withPeople);
이 부분은 생각해보겠습니다.

2024-11-14 04:13 UTC, bong94688 commented on src/test/java/bit/anniversary/controller/AnControllerTest.java
단순한 기능테스트입니다.

2024-11-14 04:13 UTC, bong94688 commented on src/test/java/bit/anniversary/controller/AnControllerTest.java
PS 포스트맨 귀찮음.

2024-11-15 07:36 UTC, rappire approved these changes
테스트쪽 코드가 아주 좋네요 LGTM!

2024-11-15 07:36 UTC, rappire commented on src/main/java/bit/anniversary/service/AnService.java
> +	public void sendAnniversaryNotification(AnResDto anniversary, String message) throws Exception {
P1 이 함수는 localhost로만 알림을 보내게 되어있는데, client ip 를 받아서 저장해야 알맞게 알림을 보낼수 있을 것 같네요.

SSE를 써보는건 어떨까요? 
https://velog.io/@bsangyong93/SSE%EB%A1%9C-%EC%95%8C%EB%A6%BC-%EA%B8%B0%EB%8A%A5-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0-feat.Spring-boot

2024-11-16 00:47 UTC, ParkSeryu approved these changes

2024-11-16 00:47 UTC, merged